---
username: "{{ ansible_env.USER }}"

path_dotfiles: "{{ playbook_dir }}/dotfiles/{{ ansible_hostname }}/"

# Relative to ansible_env.HOME
backup_targets:
  - "{{ ansible_env.HOME }}/.zshrc"
  - "{{ ansible_env.HOME }}/.tmux.conf"
