import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[env]
TERM = "screen-256color"

[window]
decorations = "None"
dynamic_padding = true
opacity = 1.0

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[selection]
save_to_clipboard = true
