import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml",
    # For non-public workstation-specific stuff
    "~/.config/alacritty/workstation-specific.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "OnlyCopy"

[window]
decorations = "None"
dynamic_padding = true
opacity = 1.0

[font]
size = 14.0

[font.bold]
family = "Fira Code"
style = "Heavy"

[font.bold_italic]
family = "Fira Code"
style = "Heavy Italic"

[font.italic]
family = "Fira Code"
style = "Medium Italic"

[font.normal]
family = "Fira Code"
style = "Medium"

[selection]
save_to_clipboard = true

[hints]
enabled = [
    { command = "xdg-open", hyperlinks = true, post_processing = true, persist = false, mouse.enabled = true, binding = { key = "U", mods = "Control|Shift" }, regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+" },
]
