---
- name: Replicate parent directory structure
  ansible.builtin.file:
    path: "{{ path_dotfiles }}/{{ path_src | dirname }}"
    state: directory
    mode: "0755"

- name: Fetch file
  ansible.builtin.fetch:
    src: "{{ path_src }}"
    dest: "{{ path_dotfiles }}/{{ path_src | realpath }}"
    flat: true
    validate_checksum: true
